repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.366
    hooks:
      - id: pyright

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix